version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 412381779393.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t etms-backend-image .
      - docker tag etms-backend-image:latest 412381779393.dkr.ecr.ap-south-1.amazonaws.com/etms-backend:latest

  post_build:
    commands:
      - echo Pushing image to AWS ECR...
      - docker push 412381779393.dkr.ecr.ap-south-1.amazonaws.com/etms-backend:latest
      - echo Build and push completed successfully.

artifacts:
  files: []
